version: '2'
services:
  postfix:
    image: smeghead/docker-postfix-tls
    environment:
      - "SMTP_USER=$SMTP_USER"
      - "SMTP_PASSWORD=$SMTP_PASSWORD"
      - "DOMAIN=$DOMAIN"
      - "RELAYHOSTPORT=$RELAYHOSTPORT"
    build: ./postfix
    depends_on:
      - maildev
  maildev:
    image: maildev/maildev
    command: >
      /bin/maildev -w $MAILDEVAPPPORT -s $RELAYHOSTPORT
    ports:
      - "1080:$MAILDEVAPPPORT"
  # command:
  #   image: harobed/docker-heirloom-mailx
  #   command: /bin/sh -c "while :; do sleep 10; done"
  app:
    image: golang:1.18-bullseye
    command: /bin/bash -c "tail -f /dev/null"
    volumes:
      - ./app/main.go:/main.go
    environment:
      - "SMTP_DOMAIN=$SMTP_DOMAIN"
      - "SMTP_PORT=$SMTP_PORT"
      - "SMTP_USER=$SMTP_USER"
      - "SMTP_PASSWORD=$SMTP_PASSWORD"
