version: '2'
services:
  postfix:
    environment:
      # DOMAIN, RELAYHOSTIP and RELAYHOSTPORT are used in run.sh (postfix container's entry point)
      - "DOMAIN=$DOMAIN"
      - "RELAYHOSTIP=${SMTP_IP}"
      - "RELAYHOSTPORT=${SMTP_PORT}"
    container_name: 'postfix'
    build: ./postfix
    # buildと共に使えば、どのディレクトリでビルドしても以下のイメージ名になるはず
    image: smeghead/docker-postfix-tls
    ports:
     - "587:587"
     - "25:25"
    networks:
      app_net:
        ipv4_address: ${POSTFIX_IP}
  smtp:
    image: schickling/mailcatcher
    container_name: 'smtp'
    ports:
     - "1080:1080"
     - "1025:${SMTP_PORT}"
    networks:
      app_net:
        ipv4_address: ${SMTP_IP}
  command:
    container_name: "command"
    image: harobed/docker-heirloom-mailx
    command: /bin/sh -c "while :; do sleep 10; done"
    networks:
      app_net:
        ipv4_address: ${COMMANDHOST_IP}
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: ${SUBNET}

# vim: set sts=2 ts=2 sw=2 expandtab:
